### PR TITLE
Box Plot

### PR DESCRIPTION
**Pull request by is**
I combined the code of bar/candlestick to implement the box, the function is basically achieved, but the code is still rough and unorganized. The documentation part also has not been added.

### CODE REVIEW

**Comment by is** [comment]
hint mode demo
```python
import plotext as plt

labels = ["apple", "bee", "cat", "dog"]
datas = [
    # max, q3, q2, q1, min
    [10, 7, 5, 3, 1.5],
    [19, 12.3, 9, 7, 4],
    [15, 14, 11, 9, 8],
    [13, 12, 11, 10, 6]]

plt.box(labels, datas, width=0.3, hint='hint')
plt.title("Most Favored Pizzas in the World")
plt.show()

```

**Comment by piccolomo** [comment]
Thank you, how do I install it though? I tried `pip install git+https://github.com/is/plotext.git` with no luck

**Comment by is** [comment]
Hi piccolomo, you  ca try this
```
pip install git+https://github.com/is/plotext.git@box
```

**Comment by piccolomo** [comment]
Hi I would be ok with it. I did not go into the details of the code,  buthere is what I need help with:

- what is `quantile` practically ?
- what is the `hint` parameter for?
- could the `candlestick` and `bar` plot functions be re-written based on the `box` function, which seems a more general version of them?
- Is there a docstring coming for the `box` method?

 
Thanks

**Comment by is** [comment]
what is quantile practically ?

> Quantile is a statistical term that divides a dataset into equal-sized portions. Practically, it is used to understand the distribution of a particular variable in a dataset. For example, if we have a large dataset of test scores, we can use quantiles to divide the scores into equal-sized portions, such as the top 25%, middle 50%, and bottom 25%. This can help us understand the distribution of scores and identify outliers or areas of strength/weakness. Quantiles are commonly used in data analysis, machine learning, and statistical modeling to understand and interpret data.

what is the hint parameter for?
> If hint == original, it will calculate max, q75, q50, q25, min based on the input data. If hint == hint, the input data is already calculated as a tuple of max, q75, q50, q25, min. Sorry for my terrible English, I don't know if there are more appropriate variable names."

could the candlestick and bar plot functions be re-written based on the box function, which seems a more general version of them?
> Based on my current understanding, the logic for box/candlestick/bar is not easily abstracted together. Unlike bar/stackbar types, box/candlestick has more specific logic. One approach that comes to mind is to provide some extension options for bar, such as callbacks and so on, to customize the details of the drawing. However, it feels like an abstraction that's not very clean or elegant.


Is there a docstring coming for the box method?
>Not yet. If there are no issues with the code details, I will complete the documentation and testing details.

**Comment by feizheng10** [comment]
Hi @piccolomo and @is,
Here are some of my thoughts and comments:
If we ONLY target on hidden outlier box plot on the 1st stage, is's implantation seems good enough.
However, interface consistency, algorithm selection, and interface extend capability are also important.  
Taking https://plotly.com/python/box-plots/ and https://matplotlib.org/3.1.1/gallery/pyplots/boxplot_demo_pyplot.html#sphx-glr-gallery-pyplots-boxplot-demo-pyplot-py as refers,
let's think about more, 
(1) For outlier points and other visualization style, I'm not sure it is good to do on text mode.
(2) Precomputed quartiles from plotly seems useful, if users don't want reply on build-in algorithm. The interface can be designed like update_traces like plotly , or add one more option to specify the data type/style(i.e. data_type=raw, or data_type=precomputed).

**Comment by piccolomo** [comment]
Hi @is, I am back on `plotext`. Are you available?

**Comment by is** [comment]
@piccolomo
It seems there is some conflict now? Let me go deal with it first.

**Comment by piccolomo** [comment]
Yes there are!

Thanks a lot  for helping. Btw, if you create a commit, not sure if you
can, but could you please call it something like "added box plot as
requested in PL 170" ?

I guess I would have to update the docstrings, documentation, updates
section and the tests.sh file.

Future idea: is a command line integration something that could be
interesting for this feature? If I would have to implement it, I will leave
it as lower priority as there is lots to be done
<https://github.com/piccolomo/plotext/blob/master/readme/notes.md#future-ideas>for
plotext, as I have been away for long time.

Thanks and all the best
- Savino

**Comment by is** [comment]
No problem, I will modify the corresponding commit log after rebasing.
I will also supplement the documentation/testing part.

**Comment by is** [comment]
@piccolomo I have rebased the code already, you can take a look at the code first and let me know if you have any feedback.

For the doc/test parts, I will push them out in separate commits later on. Once we confirm everything looks good, I will squash them together in the end.

**Comment by is** [comment]
@piccolomo 
I have noticed that the plot offset parameter has been removed in the latest master branch. What is the rationale behind this decision? Should I also remove this parameter?

**Comment by piccolomo** [comment]
oh i did not realize i did, i will double check later on today.

**Comment by piccolomo** [comment]
Hi @is, I checked and it seems that the [`draw_bar()` method](https://github.com/piccolomo/plotext/blob/f80a8fe90104efff1ad7701c519a0a427fb717c6/plotext/_monitor.py#L400) still has the offset parameter. Am I missing something?
Thanks,

**Comment by piccolomo** [comment]
Ok, everything seems good to me, except the docstring, particularly the args and hint parameter. Could you have a look?

Also could you add the example you proposed to the readme in special plots? Unless you think it should go in the bar section. and un update line in the notes.md section. I do not not how to do it myself, if you do not do some first,

Thanks for the kind help
Savino

**Comment by piccolomo** [comment]
Note: i am sure there must be a way to make a common function which `draw_box`, `draw_bar `and `draw_candlestick` rely upon, perhaps i will work on it. Something like `draw_general_bar`

**Comment by is** [comment]
I agree with your point about general bar method.

I am preparing some examples and documentation, hoping I can clearly explain the specific meaning of "hint".

**Comment by is** [comment]
May I inquire about the font you are using? The graphs I create with my current font appear incomplete and exhibit gaps in the grid, rendering them visually unappealing.

**Comment by piccolomo** [comment]
Hi @is thanks for the readme. Not sure about fonts as i do not use any, if you mean on the readme or on the plot terminal. Both terminal and readme came with their own

**Comment by is** [comment]
@piccolomo I have also added the graph to the [bar.md](http://bar.md/) file. For convenience, I have temporarily used a reference from my repository. Once the final confirmation is made before merging, I will make the necessary adjustments accordingly.

**Comment by is** [comment]
@piccolomo 
I updated the documentation for the box hint parameter, I'm not sure if I explained it clearly enough. I tried my best...
If there are no other issues, I'm going to rebase and cleanup the commits.

**Comment by feizheng10** [comment]
We might want to change the name of the parameter "hint" to something like "pre_calc".
This feature allows end users provide their customized and precalculated data just for plotting only, like plotly.
 
"pre_calc", "If pre_calc=true, the input data is an array of quintuples, each representing the precalculated maximum, third quartile(Q75), median, third quartile(Q25), and minimum values. Otherwise, plotext will calculate those based on the original  raw input data. The default value for pre_calc is false.

Does that make sense for you? @piccolomo  @is

**Comment by piccolomo** [comment]
> Does that make sense for you? @piccolomo  @is 
 it does! i now understand it!  i will come back to it also to unify the code for box bar and candlestick methods hopefully. other name (with no underscore and single clear word ) is welcomed. 

something like `auto`?

**Comment by piccolomo** [comment]
btw what would hint = "hint" do instead of hint = True? i think i have seen it somewhere?

**Comment by piccolomo** [comment]
how about the nane quintuples = True/False?

**Comment by feizheng10** [comment]
> how about the name quintuples = True/False?

Sounds good to me

**Comment by is** [comment]
@piccolomo 
I refactored the code, changed hints to quintuples, tidied things up a bit, and rebased the commits.

**Comment by piccolomo** [comment]
@is thank you for the updates; im in the process of writing a common function for bar, box and candlestick function. I will update.

**Comment by piccolomo** [comment]
Hi @is, this is requiring more time then expected as in order to join all those functions under one unifying code, requires to handle numerical, string labels and string date in the same function, which is currently not possible. So I am taking this for a deeper code update

**Comment by piccolomo** [comment]
Hi @is, Thinking about it, what I am doing will require too much time. Do your rebasing if you want, I will merge and deal with further updates on top of the merging!

thank you a lot! Waiting for update

**Comment by piccolomo** [comment]
Hi! since I was going for it, I have already updated your branch and merged to master! 

Thank you a lot for your inputs. Btw I forgot to add you to credit section. I will come back to it.

**Comment by piccolomo** [comment]
Hi @is,

  apologies for coming back to this so late, and thanks again for the code, which is what got the box plot into [plotext](https://plotext.readthedocs.io/en/latest/) in the first place.

  The plot is complete in version 6 and sits with the other bar plots, in the [box plot](https://plotext.readthedocs.io/en/latest/bar.html#box-plot) section; the details, with a picture, are in [Issue 169](https://github.com/piccolomo/plotext/issues/169).

  You are in the [credits](https://plotext.readthedocs.io/en/latest/credits.html) of the documentation for it.

  plotext 6 is out as a beta:
  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks again,
  Savino

**Pull request closed without merging**
