### PR TITLE
Add zsh completion

### PR DESCRIPTION
**Pull request by Freed-Wu**
```shell
❯ plotext <TAB>
type
bar       bar plot
gif       plays a gif image from path
hist      histogram plot
image     plots an image from file path
plot      plots lines between consecutive data points
plotter   scatter + plot
scatter   plots a series of data points
video     plays a video from path
youtube   plays a youtube video from url
❯ plotext bar --color <TAB>
color
blue+      clearer
cyan+      clearer
green+     clearer
magenta+   clearer
orange+    clearer
red+       clearer
black    blue     cyan     green    magenta  orange   red      white
❯ plotext bar --marker <TAB>
marker
at          @
atom        ⚛
bitcoin     ฿
braille     ⢕
cross       ♰
dollar      $
dot         •
...
```

### CODE REVIEW

**Comment by piccolomo** [comment]
Cool and thanks a lot for the contribution, should I merge? I did not double test it. just to let you know, that I am in the process of rewriting the code, and may try to understand what you did and perhaps tweak it. I would add you to the credit list anyway. Let me know what you think.

**Comment by Freed-Wu** [comment]
I have tested it can work. The only thing I concerned is `nargs = "+"` is not supported well. The ideal result is the following behavior is only for `-xcol`, `-ycol`, `-l`, `--lines`:

```zsh
❯ plotext bar -xcol 1 2 <TAB>
int
❯ plotext bar -xcol 1 2 -<TAB>
int
option
-c                 color of the data points in the plot, between: black,white,red,green,orange,blue,magenta,cyan; add + at the end of the color (except black and white) for clearer colors, eg: red
...
```

That is, for any option which nargs is `+`, press `-<TAB>` will stop nargs and completion other options, press `<TAB>` will still completion nargs. However, now for any options, they also have this behaviour. I advise to avoid `nargs="+"`, just use `-xcol 1,2,3` to replace `-xcol 1 2 3`, which the former is `nargs=1` and the latter is `nargs="+"`. It can avoid this problem.

If nothing will change on command line usage, I think it can be merged, and I advise to add some document to notice user how to use this new feature.

**Comment by Freed-Wu** [comment]
I found there is anther scheme: <https://github.com/iterative/shtab>

```bash
shtab --shell=zsh plotext.plotext_cli.build_parser > /usr/share/zsh/site-functions/_plotext
```

It can generate a similar zsh completion. One problem is that it cannot support choices with description:

shtab:
```
❯ plotext bar -m <TAB>
marker
at         braille    dot        fhd        four       heart      nine       one        sd         six        star       yinyang
...
```

this PR:
```
❯ plotext bar --marker <TAB>
marker
at          @
atom        ⚛
bitcoin     ฿
braille     ⢕
cross       ♰
dollar      $
dot         •
...
```

I think if this problem can be solved, it may be a more elegant solution.

**Comment by Freed-Wu** [comment]
#118

**Pull request closed without merging**
