### PR TITLE
Skip the First N Rows in read_data()

### PR DESCRIPTION
**Pull request by cwaldbieser**
Added command line flag to skip N rows.

This allows you to use a standard CSV file that has one or more header lines as input.

### CODE REVIEW

**Comment by piccolomo** [comment]
Thank you @cwaldbieser, I will eventually come back to this. I can't test your PL for now. Did you test it? Does it run smoothly? In which case I could merge already.

Thanks and all the best,
Savino

**Comment by piccolomo** [comment]
Just thinking out loud: there is a parameter in `read_data()` which is called `columns`, would it be coherent to have a similar parameter called `rows`? Not sure if it would work easily with skipping rows though.

**Comment by piccolomo** [comment]
Another idea could be to permit the `header` parameter to have also an integer value other then boolean to skip more then one line, in which case it would work as your `skip_rows` parameter, and there won't be a need for the `rows` parameter I was talking about. What do you think?

**Comment by piccolomo** [comment]
Oh, I realise now that that is what you did already, but called the parameter `skip_rows` instead of `header`. 

Anyway, if you give me an ok, I go on and merge it.

**Comment by cwaldbieser** [comment]
I ran some simple tests with a 2-column CSV file I put together:

```
x	y
1.00	12.00
2.00	27.00
3.00	52.00
4.00	87.00
5.00	132.00
6.00	187.00
7.00	252.00
8.00	327.00
9.00	412.00
10.00	507.00
11.00	612.00
12.00	727.00
13.00	852.00
14.00	987.00
15.00	1132.00
16.00	1287.00
17.00	1452.00
18.00	1627.00
19.00	1812.00
20.00	2007.00
21.00	2212.00
```
The actual file is comma-separated; the above is tab separated to read a little easier.

The following makes a nice plot:

```sh
$ plotext plot -xcol 1 -r 1 -p ~/datasets/misc/scatter.csv -d ','
```

**Comment by piccolomo** [comment]
Good one.

**Comment by piccolomo** [comment]
Hi I have updated the packed, and called the very same parameter `first_row`: you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Here are the download instruction [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#install).

Thank you a lot for the help.
Savino

**Comment by piccolomo** [comment]
Hi @cwaldbieser, and sorry for the very late thanks.

  Your patch went in as `first_row` in version 5. Version 6 of [plotext](https://plotext.readthedocs.io/en/latest/) handles it differently, reading the file and drawing the plot as two separate steps, so skipping rows is a slice on your side: I have written the whole answer in #165, together with two faults   your question uncovered in the reader.

  plotext 6 is out as a beta:

  - GitHub: https://github.com/piccolomo/plotext
  - PyPI: https://pypi.org/project/plotext/6.0.0b0/, installed with `pip install --pre plotext`
  - documentation: https://plotext.readthedocs.io/en/latest/

  Thanks for writing it,

  Regards,
  Savino

**Pull request merged**
