### PR TITLE
Add shtab as an extra_require

### PR DESCRIPTION
**Pull request by Freed-Wu**
:cry: I am sorry for `git commit --amend` incorrectly in the last pr.

This pr uses  `try/except` to make it work when shtab is not installed.

### CODE REVIEW

**Comment by piccolomo** [comment]
no problem, i am taking more time on this one, also resting after latest upload. 

are you sure that the .complete() part will not create problems when shtab is not installed? that looks like a method from shtab, no?

**Comment by Freed-Wu** [comment]
I am sure. `_shtab.py` will create `.complete` to avoid the bug.

**Comment by piccolomo** [comment]
cool, i merge and will check later. and upload to pypi eventually after few other bugs. thanks a lot

**Comment by piccolomo** [comment]
ps i am a disaster with git, not sure if when i upload my code i will overwrite your changes. but if you have any tip on how to upload on terminal without embaracements, welcome!

**Comment by piccolomo** [comment]
Hi @Freed-Wu,

I have finally updated my GitHub repository and leaned some git. I had lost the repo history and I have reconstructed what I could, but in doing so I was not able to retrieve your PL (as well as all others) in the commit list. You changes should be included and I will credit you more formally in the notes soon. 

Hopefully this won't happen again now that I know the basic of git.

Thanks a lot for your contribution,
Savino

**Comment by piccolomo** [comment]
Hi @Freed-Wu,

I have credited you [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Thanks for the contribution. 
Savino

**Pull request merged**
