### PR TITLE
Refactor cli

### PR DESCRIPTION
**Pull request by asartori86**
@piccolomo, I've implemented what you asked in #51 

```
$ plotext -h
usage: plotext [-h] [-f FILE] [-d DELIMITER] [-c [COLUMNS [COLUMNS ...]]]
               [--bins BINS] [-s SIZE] [-xl [XLABEL]] [-yl [YLABEL]]
               [-t [TITLE]] [-g]
               {scatter,bar,line,linespoints,hist}

plots directly on the terminal

positional arguments:
  {scatter,bar,line,linespoints,hist}

optional arguments:
  -h, --help            show this help message and exit
  -f FILE, --file FILE  Read data from FILE. If this flag is not used, plotext
                        reads from stdin
  -d DELIMITER, --delimiter DELIMITER
                        Use DELIMITER instead of spaces for column separator
  -c [COLUMNS [COLUMNS ...]], --columns [COLUMNS [COLUMNS ...]]
                        Columns to plot. For scatter, line, linespoints, and
                        bar, they must be pairs separated by ',' without
                        spaces 1,2 1,3 4,2. For histogram plots, list of
                        columns 1 2 3. By default, the first two columns are
                        used
  --bins BINS           Number of bins for histogram plot
  -s SIZE, --size SIZE  Size of the plot
  -xl [XLABEL], --xlabel [XLABEL]
                        Set x label
  -yl [YLABEL], --ylabel [YLABEL]
                        Set y label
  -t [TITLE], --title [TITLE]
                        Set plot title
  -g, --grid            Enable grid

    examples:

    # plot data from stdin
    $ cat data.txt | plotext scatter

    # plot data from a file
    $ plotext scatter -f data.txt

    # bar plot of second-first column
    $ cat data.txt | plotext bar --columns 2,1

    # linespoints of first-second and first-third column
    $ plotext linespoints -f data.txt --columns 1,2 1,3

    # histogram plot. columns are separated by ,
    $ plotext hist -f data.csv -d , -c 1 2

```

### CODE REVIEW

**Comment by asartori86** [comment]
@piccolomo,
you force-pushed a new history :-| 

Why didn't you open PRs for that development? now all the development that has been done in between is lost

**Comment by piccolomo** [comment]
Hi Alberto,

sorry I am not particularly experienced with GitHub. Any way that is why I
asked you before. And I thought that I followed your instructions actually.

- Savino

**Comment by piccolomo** [comment]
Hi Alberto, I should apologise, I did not expect to cause that much trouble. As I said, I am not an expert either in Python or Github.
Aa I understood, I tought you agreed on me upload the new version of the package.

This is the sequence of terminal command I use to publish on GitHub:
```
git config --global user.email "piccolomo@gmail.com"
git init
git add .
git commit -m "commit new message"
git remote rm origin
git remote add origin "https://github.com/piccolomo/${package_name}.git"
git push -f origin master
```

Please let me know if you spot some issues in this commands. Thanks and hope to see your pull request again.
Savino

**Comment by asartori86** [comment]
> Hi Alberto, I should apologise, I did not expect to cause that much trouble. As I said, I am not an expert either in Python or Github. Aa I understood, I tought you agreed on me uploading the new version of the package.
> 
> This is the sequence of terminal command I use to publish on GitHub:
> 
> ```
> git config --global user.email "piccolomo@gmail.com"
> git init
> git add .
> git commit -m "commit new message"
> git remote rm origin
> git remote add origin "https://github.com/piccolomo/plotext.git"
> git push -f origin master
> ```
> 
> Please let me know if you spot some issues in these commands. Thanks and hope to see your pull request again. Savino

Ciao Savino,
yes, the issue is that you use a new git repo, and in this way, you lose all the history of the previous version.

git is a version control system, meaning that it can (and should) remember each modification you do on the code. So, you should clone the repo once, and then always work within the same folder, use new branches, and merge them from github opening pull requests. 

this is a good intro to git https://swcarpentry.github.io/git-novice/

this is a more detailed ref https://git-scm.com/book/en/v2

let me know if I can help you in becoming a git ninja :)

**Pull request closed without merging**
