### PR TITLE
Add bash/zsh/tcsh completion by shtab

### PR DESCRIPTION
**Pull request by Freed-Wu**
However, import a new independence. If you don't mind, merge this PR and close
another PR.

### CODE REVIEW

**Comment by piccolomo** [comment]
I will test this later and report... thanks a lot for the contribution!!! Highly appreciated.

**Comment by Freed-Wu** [comment]
:smile: You can change shtab to an optional depend, such as `pip install plotext[completion]`, that is when shtab is installed, plotext supports the generation of shell completions.

**Comment by piccolomo** [comment]
Hi @Freed-Wu,

I am in the process of upgrading `plotext` and integrating your changes. I have tried the packed as you have changed it, but when i press TAB after `plotext` command on any sub-command nothing happens. I have installed `shtab`.

Does it work for you? Any help?

**Comment by piccolomo** [comment]
To be precise, when I press TAB (eg after `plotext` or after `plotex scatter`) a series of options not connected to `plotext` appear, like directories and files.

**Comment by Freed-Wu** [comment]
Which shell do you use? Take zsh as an example:

```shell
plotext --print-completion zsh| sudo tee /usr/share/zsh/site-functions/_plotext
# maybe
plotext --print-completion zsh| sudo tee /usr/local/share/zsh/site-functions/_plotext
```

**Important**

Then `compinit` to generate `~/.zompdump`

```bash
❯ grep _plotext ~/.zcompdump
'plotext' '_plotext'
```

That means plotext has a completion named _plotext.

If don't have `_plotext`, you can `rm ~/.zompdump` then retry `compinit`

Then it should work.

```shell
❯ plotext <TAB>
plotext commands
bar       builds a bar plot
gif       plays a gif image from path
hist      builds a histogram plot
image     plots an image from path
plot      plots lines between consecutive data points
plotter   plots a series of data points and the lines between consecutive ones
scatter   plots a series of data points
video     plays a video from path
youtube   plays a youtube video from url
```

**Comment by piccolomo** [comment]
Hi thanks for the message, I find it hard to understand it as I am fresh and new to completions. 

I am using `bash`. And cannot find the _plotext file. I have tried around here:

`plotext --print-completion bash | sudo tee /usr/share/bash-completion/completions/`

Also the command `compinit`  does not compute in my system. Would this be something that the user would have to do? in which case it could be tricky on them.

**Comment by Freed-Wu** [comment]
For bash:

```
plotext --print-completion bash|sudo tee /usr/share/bash-completion/completions/plotext
```

I test it can work (although don't have too many functions as zsh)

Screenshot from 2022-09-01 23-43-56

**Comment by Freed-Wu** [comment]
> Then compinit to generate ~/.zompdump

`compinit` is a zsh command, zsh will generate a cache to help fasten the completion. if the cache has wrong information, it cannot work. bash will not use any cache.

**Comment by piccolomo** [comment]
I run the following
image
with no result in terms of tab completion

**Comment by Freed-Wu** [comment]
Can you `cat /usr/share/bash-completion/completions/plotext`?

**Comment by piccolomo** [comment]
yes
image

**Comment by Freed-Wu** [comment]
Have you installed `bash-completion`?

**Comment by piccolomo** [comment]
I have just now installed bash-completion and then x264, but when I press x624 -- <TAB> nothing happens... no options displayed.

**Comment by piccolomo** [comment]
Ok I have tried a new terminal called Konsole and I have completion but the only marker it completes is hd
image

**Comment by Freed-Wu** [comment]
I guess your bashrc don't load bash-completion. Can you add `[ -r /usr/share/bash-completion/bash_completion   ] && . /usr/share/bash-completion/bash_completion` to your bashrc and retry?

**Comment by piccolomo** [comment]
Ok now it works also in my normal ubuntu terminal but it has the same limitations as Konsole... completion yes but no list of possibilities

**Comment by Freed-Wu** [comment]
> I have completion but the only marker it completes is sd: it does not display a list of possibilities

See <https://github.com/iterative/shtab/issues/86>, it is a bug imported from <https://github.com/iterative/shtab/issues/81>

> only expands the first value of the _choices array.

**Comment by piccolomo** [comment]
Mmm, ok thanks then. It seems we could only wait and hope the issue gets solved. Thanks btw

**Comment by Freed-Wu** [comment]
You are welcome! :smile:

**Comment by piccolomo** [comment]
Just to add a final note: markers and colors are completed only in their first element and the code works the same as when i remove the .complete part... so I take it away for now and comment the function `dict_to_complete`

**Comment by piccolomo** [comment]
Hi @Freed-Wu , I finally updated `plotext` including the changes you asked for. 

The new version is available [on GitHib](https://github.com/piccolomo/plotext) for now and soon also [on PyPi](https://pypi.org/project/plotext/). To install follow the indications [here](https://github.com/piccolomo/plotext#install).

Your changes are documented [here](https://github.com/piccolomo/plotext/blob/master/readme/utilities.md#command-line-tool) and you have been credited [here](https://github.com/piccolomo/plotext/blob/master/readme/notes.md#credits).

Any feedback is welcomed.

Thanks a lot for your inputs and all the best,
Savino

**Comment by piccolomo** [comment]
Sorry @Freed-Wu , as I have been warned, I had to removed the `shtab` dependency because it cannot be made optional, since it is called once `plotext.cli.py` is loaded.

If you have any other idea, very welcomed. Thanks

**Comment by Freed-Wu** [comment]
> because it cannot be made optional, since it is called once plotext.cli.py is loaded.

```python
try:
    import shtab
except ImportError:
    from . import _shtab as shtab
```

Then realize a internal module named `_shtab.py` which just provide a same API 
with `shtab`

**Pull request merged**
